# Generated by Django 3.1.6 on 2021-02-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupdata',
            name='Email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
