# Generated by Django 3.1.6 on 2021-02-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionapp', '0006_remove_signupdata_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupdata',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=10),
        ),
    ]
